In [1]:
import requests
import json
from pprint import pprint
import pandas as pd
from tabulate import tabulate
import pprint

In [41]:
use_cols = ['Material_ID','Customer','Cal_year_month', 'Gross_Bookings_Qty_CRD']
dtype= {'Material_ID':str,'Customer':str}

In [49]:
bas_s3_pth = 's3://kbs-prediction-service-molex/APS/'
bas_europe_pth = 's3://kbs-prediction-service-molex/EUR/'
europe_file_name='monthly_agg_SKU_CUST_EUR.csv'
f'{bas_europe_pth}{europe_file_name}'

's3://kbs-prediction-service-molex/EUR/monthly_agg_SKU_CUST_EUR.csv'

In [43]:
raw_dat = pd.read_csv('s3://kbs-prediction-service-molex/APS/monthly_agg_SKU_CUST_APS.csv', 
                      parse_dates=['Cal_year_month'], usecols=use_cols, dtype=dtype)
raw_dat.rename(columns={'Cal_year_month':'Date'}, inplace=True)
raw_dat.tail()

       Material_ID Customer       Date  Gross_Bookings_Qty_CRD
356851   989971002   157988 2018-12-01                     0.0
356852   989971002   157988 2020-04-01                     0.0
356853   989971002   157988 2020-05-01                     0.0
356854   989971002   157988 2020-06-01                     0.0
356855   989971002   167659 2018-12-01                 20400.0

In [44]:
raw_dat.shape

(356856, 4)

In [45]:
raw_dat['index'] = raw_dat[['Material_ID','Customer']].apply(lambda x: '-'.join(x),axis=1)

In [46]:
proc_dat = raw_dat.groupby(['index', 'Date']).sum().unstack([0]).fillna(0)

In [47]:
proc_dat.tail()

           Gross_Bookings_Qty_CRD                                      \
index           1041330227-128380 1041330227-136759 1042126411-109606
Date
2020-09-01                    0.0               0.0               0.0
2020-10-01                    0.0               0.0               0.0
2020-11-01                    0.0               0.0               0.0
2020-12-01                    0.0               0.0               0.0
2021-01-01                    0.0               0.0               0.0

                                                                  \
index      1042126411-111658 1042126411-113100 1042126411-130300
Date
2020-09-01               0.0               0.0               0.0
2020-10-01               0.0               0.0               0.0
2020-11-01               0.0               0.0            1260.0
2020-12-01               0.0               0.0            2520.0
2021-01-01               0.0               0.0               0.0

                                                                  \
index      1042126411-135809 1042126411-147208 1042126411-157185
Date
2020-09-01               0.0               0.0               0.0
2020-10-01               0.0               0.0               0.0
2020-11-01               0.0               0.0               0.0
2020-12-01               0.0               0.0               0.0
2021-01-01               0.0               0.0               0.0

                              ...                                    \
index      1042126411-157305  ... 989952029-145549 989952029-165959
Date                          ...
2020-09-01               0.0  ...              0.0              0.0
2020-10-01               0.0  ...              0.0              0.0
2020-11-01               0.0  ...              0.0              0.0
2020-12-01               0.0  ...              0.0              0.0
2021-01-01               0.0  ...              0.0              0.0

                                                               \
index      989971002-111658 989971002-115119 989971002-118272
Date
2020-09-01              0.0              0.0              0.0
2020-10-01              0.0              0.0              0.0
2020-11-01              0.0              0.0              0.0
2020-12-01              0.0              0.0              0.0
2021-01-01              0.0              0.0              0.0

                                                               \
index      989971002-133355 989971002-156704 989971002-157185
Date
2020-09-01              0.0              0.0              0.0
2020-10-01              0.0              0.0              0.0
2020-11-01              0.0              0.0              0.0
2020-12-01              0.0              0.0              0.0
2021-01-01              0.0              0.0              0.0


index      989971002-157988 989971002-167659
Date
2020-09-01              0.0              0.0
2020-10-01              0.0              0.0
2020-11-01              0.0              0.0
2020-12-01              0.0              0.0
2021-01-01              0.0              0.0

[5 rows x 27320 columns]

In [48]:
proc_dat.columns = proc_dat.columns.droplevel([0])
proc_dat.columns.name =None
proc_dat.shape

(97, 27320)

In [49]:
proc_dat.head()

,1041330227-128380,1041330227-136759,1042126411-109606,1042126411-111658,1042126411-113100,1042126411-130300,1042126411-135809,1042126411-147208,1042126411-157185,1042126411-157305,...,989952029-145549,989952029-165959,989971002-111658,989971002-115119,989971002-118272,989971002-133355,989971002-156704,989971002-157185,989971002-157988,989971002-167659
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-04-01,2400.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2013-05-01,2400.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
##proc_dat.value_counts()
##proc_dat.describe()
df = proc_dat.loc[:, (proc_dat == 0).mean() < .7]
##df.shape
df.head()

,1480100002-134880,1480102100-134880,1480103100-134880,1480150001-160392,1480150001-160436,1480170003-134880,1480260001-134880,1480260005-134880,1480260009-134880,1480260013-134880,...,989943011-130201,989943011-145549,989951021-130201,989951021-145549,989951029-130201,989951101-130201,989951101-145549,989952021-130201,989952021-145549,989952029-130201
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2976.0,4836.0,0.0,0.0,0.0,850.0,4250.0,0.0,0.0,0.0
2013-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2604.0,1488.0,0.0,0.0,0.0,850.0,850.0,0.0,0.0,0.0
2013-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5580.0,3720.0,0.0,0.0,0.0,4250.0,3400.0,0.0,0.0,0.0
2013-04-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2604.0,5208.0,0.0,0.0,0.0,6800.0,3400.0,0.0,0.0,0.0
2013-05-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1860.0,5208.0,0.0,0.0,0.0,8500.0,4250.0,0.0,0.0,0.0

In [58]:
file_name = "proc_SKU_CUST_APS_remove-zeros.csv"
##file_name = "proc_SKU_CUST_APS.csv"
sav_pth = 's3://kbs-prediction-service-molex/APS/' + file_name
europe_filter_path='proc_SKU_CUST_EUR_fltr.csv'
europe_sav_path = f'{bas_europe_pth}{europe_filter_path}'
loc_path = "/home/ubuntu/work/kgsa-core-prediction/tests/resources/data/" + file_name
##proc_dat.to_csv(sav_pth)
print(europe_sav_path)

s3://kbs-prediction-service-molex/EUR/proc_SKU_CUST_EUR_fltr.csv

In [61]:
##proc_dat.to_csv(loc_path)
##df.to_csv(loc_path)
##df.to_csv(sav_pth)

# Setup

In [32]:
Baseurl = 'https://kgsa-dev.kochcloud.com' #/review' ##/badrul'
Baseurl2 = 'https://kgsa-dev.kochcloud.com/badrul' #/review' ##/badrul'
user = 'bibin'
password = "3$7AdE9OIJ6M1X*QUfuhD"

# Model Training

### C3 FHR Data

#### Data Format
1. **First column** - should be a datetime column

In [62]:
## TODO: Read in the data and show the head
fhrDf = pd.read_csv(sav_pth, sep=',', header = 0, index_col = 0)
fhrDf.index = pd.to_datetime(fhrDf.index)
fhrDf.head()

,1480100002-134880,1480102100-134880,1480103100-134880,1480150001-160392,1480150001-160436,1480170003-134880,1480260001-134880,1480260005-134880,1480260009-134880,1480260013-134880,...,989943011-130201,989943011-145549,989951021-130201,989951021-145549,989951029-130201,989951101-130201,989951101-145549,989952021-130201,989952021-145549,989952029-130201
Date,,,,,,,,,,,,,,,,,,,,,
2013-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2976.0,4836.0,0.0,0.0,0.0,850.0,4250.0,0.0,0.0,0.0
2013-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2604.0,1488.0,0.0,0.0,0.0,850.0,850.0,0.0,0.0,0.0
2013-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5580.0,3720.0,0.0,0.0,0.0,4250.0,3400.0,0.0,0.0,0.0
2013-04-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2604.0,5208.0,0.0,0.0,0.0,6800.0,3400.0,0.0,0.0,0.0
2013-05-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1860.0,5208.0,0.0,0.0,0.0,8500.0,4250.0,0.0,0.0,0.0

In [23]:
print(tabulate(fhrDf, headers='keys', tablefmt='psql'))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

### Training Parameters
Dictionary below contains the minimum configuration needed to run a training job.

In [94]:
# trainingDict = {
#         "training": {
#             "train_name": "ps-jupyter-molex-APs-subset-trial", 
#             "target_data_location": "s3://kbs-prediction-service-molex/monthly_molex_SKU_PS.csv",
#             "train_data_end_dtm": "2020-04-01",
#             "test_data_end_dtm": "2020-07-01",
#             "validation_data_end_dtm": "2021-01-01",
#             "model_names": ["ARIMA", "HOLTWINTERS", "PROPHET"]
#         }
#     }



trainingDict = {
    "master": {
    "exec_environment": "Sequential",
    "data_storage_type": "s3",
    "data_file_type": "csv",
    },
    
    "training": {
    "train_name": "ps-jupyter-molex-APS-subset-trial",
    "train_description": "Molex APS data training for ARIMA, HOLT, and PROPHET",
    "train_task_type": "Model",
    "train_job_type": "Single-Target",
    "target_data_location": f"{sav_pth}",
    "feature_data_location": "",
    "score_data_location": f"{bas_s3_pth}results/",
    "model_version": "pred-manager-molex-test",
    "data_version": "v1.0",
    "loss_function": "MAPE",
    "train_data_end_dtm": "2020-04-01",
    "test_data_end_dtm": "2020-07-01",
    "validation_data_end_dtm": "2021-01-01",
    "model_location": f"{bas_s3_pth}model/",
    "time_interval": "M",
    "model_names": ["ARIMA", "HOLTWINTERS", "PROPHET"],
    }
}

trainingDict

{'master': {'exec_environment': 'Sequential',
  'data_storage_type': 's3',
  'data_file_type': 'csv'},
 'training': {'train_name': 'ps-jupyter-molex-APS-subset-trial',
  'train_description': 'Molex APS data training for ARIMA, HOLT, and PROPHET',
  'train_task_type': 'Model',
  'train_job_type': 'Single-Target',
  'target_data_location': 's3://kbs-prediction-service-molex/APS/proc_SKU_CUST_APS.csv',
  'feature_data_location': '',
  'score_data_location': 's3://kbs-prediction-service-molex/APS/results/',
  'model_version': 'pred-manager-molex-test',
  'data_version': 'v1.0',
  'loss_function': 'MAPE',
  'train_data_end_dtm': '2020-04-01',
  'test_data_end_dtm': '2020-07-01',
  'validation_data_end_dtm': '2021-01-01',
  'model_location': 's3://kbs-prediction-service-molex/APS/model/',
  'time_interval': 'M',
  'model_names': ['ARIMA', 'HOLTWINTERS', 'PROPHET']}}

### Executing Training Job

In [95]:
response = requests.post(Baseurl+"/training", 
                         auth=(user, password),
#                          data = json.dumps(trainingDict))  
                         json = trainingDict)

### Checking Training Status

In [96]:
print(response)
result = response.json()
print(pprint.pprint(result))
trainingId = result['runId']
print(trainingId)

<Response [200]>
{'runId': '16f5e3fc-072b-4a84-ac3f-a36b65d9ab02', 'status': 'Submitted'}
None
16f5e3fc-072b-4a84-ac3f-a36b65d9ab02

#### Result of Calling the Training Job

The training is executed asynchronously.  This end point submits the job to the prediction service which gets queued and run as resource become available.  Thus, the end point returns a **runId** which is needed to get status, training results or use the trained model for prediction

In [70]:
status_response = requests.get(Baseurl+"/trainings/" + trainingId,
                              auth=(user,password))    
print(status_response)

<Response [200]>

In [71]:
trainingStatus = status_response.json()
print(pprint.pprint(trainingStatus))

{'runId': '67bd05b5-c538-429e-90da-bbab3994613c',
 'status': 'Submitted',
 'trainStartTs': '2021-02-21T03:30:57.070982',
 'updateTs': '2021-02-21T03:30:57.087657'}
None

#### Parameters Returned by Status Call

1. **runId** - This is an UUID that uniquely identifies each training job.  This UUID is **very important** as all subsequent information and result of training is identified using the UUID.  The UUID can also be used during prediction to use the model trained
2. **status**: Current status of the training
3. **trainStartTs**: Timestamp of the training start

### Extracting Training Results

In [78]:
resultResponse = requests.get(Baseurl+"/trainings/"+ trainingId,
                              auth=(user,password))    
print(resultResponse)
trainResults = resultResponse.json()
print(pprint.pprint(trainResults))

<Response [200]>
{'resultLocation': 's3://prediction-services/train/TUNING-arima-holt-prophet-molex-APS-test_08c5483f-75db-4d00-a3b9-b89e99954cb6_2021-02-19-11.37.20.csv',
 'runId': '08c5483f-75db-4d00-a3b9-b89e99954cb6',
 'status': 'Failed',
 'trainEndTs': '2021-02-19T11:37:20.618177',
 'trainStartTs': '2021-02-19T11:37:20.392291',
 'updateTs': '2021-02-19T11:37:20.361558'}
None

In [99]:
results = pd.read_csv('s3://prediction-services/score/ps-jupyter-molex-APs-subset-trial_6ce28301-36bf-4469-a441-29977b5bef31_2021-02-18-16.24.53.csv')

In [100]:
results

,target_column,train_start_ts,train_end_ts,model,model_params,train_score,test_score,validation_score
0,307004100,2021-02-18 16:24:53.590122,2021-02-18 16:27:18.044643,HOLTWINTERS,"{'parameters': {'trend': 'add', 'damped': True...",0.226366,0.107954,0.063172
1,310343018,2021-02-18 16:24:53.590122,2021-02-18 16:30:53.805674,HOLTWINTERS,"{'parameters': {'trend': 'add', 'damped': True...",0.037119,0.109149,0.067250
2,311010040,2021-02-18 16:24:53.590122,2021-02-18 16:34:29.520690,HOLTWINTERS,"{'parameters': {'trend': 'add', 'damped': True...",1.000000,1.000000,0.188026
3,307001168,2021-02-18 16:24:53.590122,2021-02-18 16:26:06.939456,HOLTWINTERS,"{'parameters': {'trend': 'add', 'damped': True...",0.201774,0.299228,1.000000
4,309681127,2021-02-18 16:24:53.590122,2021-02-18 16:29:44.456867,HOLTWINTERS,"{'parameters': {'trend': 'add', 'damped': True...",0.145935,0.294999,1.000000
...,...,...,...,...,...,...,...,...
295,310343016,2021-02-18 16:24:53.590122,2021-02-18 16:30:53.474015,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",1.000000,1.000000,1.000000
296,311000040,2021-02-18 16:24:53.590122,2021-02-18 16:34:29.180089,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",1.000000,1.000000,1.000000
297,307001167,2021-02-18 16:24:53.590122,2021-02-18 16:26:06.697487,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",0.627410,0.628235,1.000000
298,309681126,2021-02-18 16:24:53.590122,2021-02-18 16:29:44.179773,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",1.000000,1.000000,1.000000
299,310681071,2021-02-18 16:24:53.590122,2021-02-18 16:33:17.949174,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",0.003604,0.170650,0.059692

#### Training Result Information

Paramters Explnation:
1. **status** - Status of the training job.
2. **resultLocation** - S3 location where training scores will be stored once the training has completed

In [24]:
##TODO: Read in the forecast results and show 
trainResultLoc = trainResults['resultLocation']
##trainResultLoc = 's3://prediction-services/train/model-minimum-config-jupyter_d1fe11ae-27dc-44ca-93aa-9ba367786872_2021-01-29-20.52.29.csv'
trainDf = pd.read_csv(trainResultLoc, sep=',', header = 0)
trainDf.head()
##fhrDf.index = pd.to_datetime(fhrDf.index)
##print(tabulate(trainDf, headers='keys', tablefmt='psql'))

,target_column,train_start_ts,train_end_ts,model,model_params,train_score,test_score,validation_score
0,53511-10483,2021-02-17 03:51:37.069228,2021-02-17 03:51:53.612120,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",0.068470,0.154862,1.000000
1,53511-3553,2021-02-17 03:51:37.069228,2021-02-17 03:52:04.359351,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",1.000000,1.000000,1.000000
2,53511-3802,2021-02-17 03:51:37.069228,2021-02-17 03:52:09.724905,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",0.775224,0.611006,0.659785
3,53511-4773,2021-02-17 03:51:37.069228,2021-02-17 03:52:15.311753,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",0.249423,0.247317,1.000000
4,34883-3350,2021-02-17 03:51:37.069228,2021-02-17 03:51:48.232401,PROPHET,"{'parameters': {'growth': 'linear', 'holidays'...",0.685172,1.000000,0.259096

# Model Tuning and Experimentation

#### Hyperparameter Tuning Introduction
**Tuning jobs scale by**:
1. Scaling up or Vertical Scaling - Parallel or
2. Scaling out or Horizontal Scaling - Distributed

Univariate models execute independently.  For each server number of models being tuned simultaneously is limited by number of CPUs on the server

**Deep Learning Models and Parameter Server**
A parameter server typically exists as a remote process or service and interacts with clients through remote procedure calls.

Image(filename=images/param-server-arch.jpg)

![Parameter Server Architecture](images/param-server-arch.jpg)

For hyperparameter tuning a search space of paerameters has to be defined.

##### Search Algorithms
Search Algorithms are wrappers around open-source optimization libraries for efficient hyperparameter selection.

Search Algorithms cannot affect or stop training processes. However, you can use them together to early stop the evaluation of bad trials.

1. **Bayesian Optimization**: This constrained global optimization process builds upon bayesian inference and gaussian processes. It attempts to find the maximum value of an unknown function in as few iterations as possible. This is a good technique for optimization of high cost functions.
2. **BOHB (Bayesian Optimization HyperBand)**: An algorithm that both terminates bad trials and also uses Bayesian Optimization to improve the hyperparameter search. It is backed by the HpBandSter library. BOHB is intended to be paired with a specific scheduler class: HyperBandForBOHB.
3. **HyperOpt**: A Python library for serial and parallel optimization over awkward search spaces, which may include real-valued, discrete, and conditional dimensions.
4. **Scikit-Optimize*:
5. **Nevergrad**: HPO without computing gradients.


##### Schedulers
Schedulers are distributed implementations of early-stopping algorithm
Schedulers can early terminate bad trials, pause trials, clone trials, and alter hyperparameters of a running trial.

1. **Median Stopping Rule**: It applies the simple rule that a trial is aborted if the results are trending below the median of the previous trials.
2. **Population Based Training (PBT)** - 
3. **FIFOScheduler* - Simple scheduler that just runs trials in submission order

#### Experiment Execution

### Tuning Parameters
Dictionary below contains the minimum configuration needed to run a tuning job.

In [40]:
trainingDict = {
        "training": {
            "train_task_type": "Tuning",
            "train_name": "TUNING-arima-holt-prophet-molex-APS-test", 
            "target_data_location": f"{sav_pth}",
            "loss_function": "MAPE",
            "train_data_end_dtm": "2020-04-01",
            "test_data_end_dtm": "2020-07-01",
            "validation_data_end_dtm": "2021-01-01",
            "model_names": ["ARIMA"]
        },
        "models": {
            "ARIMA": {
            "model_name": "ARIMA",
            "model_time_interval": "M",
            "hyperparam_alg": "GRID-SEARCH",
            "model_config": {
                "parameters": {"p": [0,1,2,3,4,5,6], "d": [0,1,2,3,4,5,6], "q": [0, 1,2,3,4,5,6]},
                "hyperparameters": {"disp": 0}}
            }
        }
    }
response = requests.post(Baseurl2+"/training", 
                         auth=(user, password),
                         data = json.dumps(trainingDict))  
                         #json = trainingDict)

In [41]:
# pprint.pprint(trainingDict)

#### Tuning Configuration Explanation
##### Required Parameters
1. **train_task_type** = "TUNING"
    * By default it's set to "MODEL"
2. **All the parameters mentioned in the training section**

##### Optional Parameters
1. **hyperparameter_algorithm** -

In [42]:
print(response)
result = response.json()
print(pprint.pprint(result))
trainingId = result['runId']
print(trainingId)

<Response [200]>
{'runId': 'b81ad256-8e2f-498f-8b4b-0a938ccac4c4', 'status': 'Submitted'}
None
b81ad256-8e2f-498f-8b4b-0a938ccac4c4

In [71]:
resultResponse = requests.get(Baseurl+"/trainings/"+ trainingId,
                              auth=(user,password))
print(resultResponse)
trainResults = resultResponse.json()
print(pprint.pprint(trainResults))

<Response [200]>
{'resultLocation': 's3://prediction-services/train/TUNING-arima-holt-prophet-molex-APS-test_08c5483f-75db-4d00-a3b9-b89e99954cb6_2021-02-19-11.37.20.csv',
 'runId': '08c5483f-75db-4d00-a3b9-b89e99954cb6',
 'status': 'Failed',
 'trainEndTs': '2021-02-19T11:37:20.618177',
 'trainStartTs': '2021-02-19T11:37:20.392291',
 'updateTs': '2021-02-19T11:37:20.361558'}
None

# Prediction or Scoring

## Scoring Parameters - Europe

In [59]:
scoringDict = {
        "scoring": {
            "score_name": "Molex-SCORING-Europ-Non-Zero",
            "target_data_location": europe_sav_path,
            "model_names": ["ARIMA", "HOLTWINTERS", "PROPHET"],
            "prediction_steps": 4,
            "prediction_count": 1
            
        }
    }

scoringDict

{'scoring': {'score_name': 'Molex-SCORING-Europ-Non-Zero',
  'target_data_location': 's3://kbs-prediction-service-molex/EUR/proc_SKU_CUST_EUR_fltr.csv',
  'model_names': ['ARIMA', 'HOLTWINTERS', 'PROPHET'],
  'prediction_steps': 4,
  'prediction_count': 1}}

In [60]:
predResponse = requests.post(Baseurl + "/predictions", 
                         auth=(user, password),
                         data = json.dumps(scoringDict))

In [61]:
print(predResponse)
predResults = predResponse.json()
##print(predResults)
print(pprint.pprint(predResults))
predId = predResults['runId']
print(predId)

<Response [200]>
{'runId': '14c0f06c-ec81-4c7d-bda1-0e16c1813d2a', 'status': 'Created'}
None
14c0f06c-ec81-4c7d-bda1-0e16c1813d2a

In [62]:
predResponse = requests.get(Baseurl+"/fetch_predictions/"+ predId,
                              auth=(user,password))    
print(predResponse)
predStatus = predResponse.json()
print(pprint.pprint(predStatus))
predId = predStatus['runId']
print(predId)

<Response [200]>
{'runId': '14c0f06c-ec81-4c7d-bda1-0e16c1813d2a', 'status': 'Submitted'}
None
14c0f06c-ec81-4c7d-bda1-0e16c1813d2a

## Scoring Parameters - APS
Dictionary below contains the minimum configuration needed to run a scoring job.

In [63]:
scoringDict2 = {
        "scoring": {
            "score_name": "Molex-SCORING-APS-Non-Zero",
            "target_data_location": sav_pth,
            "model_names": ["ARIMA", "HOLTWINTERS", "PROPHET"],
            "prediction_steps": 4,
            "prediction_count": 1
            
        }
    }

predResponse2 = requests.post(Baseurl + "/predictions", 
                         auth=(user, password),
                         data = json.dumps(scoringDict2))

In [64]:
##predResponse2 = predResponse
print(predResponse2)
predResults2 = predResponse2.json()
##print(predResults)
print(pprint.pprint(predResults2))
predId2 = predResults2['runId']
print(predId2)

<Response [200]>
{'runId': '486d4df4-f582-4ea3-8bb9-b41ed6564488', 'status': 'Created'}
None
486d4df4-f582-4ea3-8bb9-b41ed6564488

### Get Prediction Status

In [65]:
predResponse2 = requests.get(Baseurl+"/fetch_predictions/"+ predId2,
                              auth=(user,password))    
print(predResponse2)
predStatus2 = predResponse2.json()
print(pprint.pprint(predStatus2))
predId2 = predStatus2['runId']
print(predId2)

<Response [200]>
{'runId': '486d4df4-f582-4ea3-8bb9-b41ed6564488', 'status': 'Running'}
None
486d4df4-f582-4ea3-8bb9-b41ed6564488

### Fetch Prediction Results

In [77]:
predResponse = requests.get(Baseurl+"/predictions/"+ predId,
                              auth=(user,password))    
print(predResponse)
predResults = predResponse.json()
##print(predResults)
print(pprint.pprint(predResults))
predLoc = predResults["resultLocation"]
print(predLoc)

<Response [200]>
{'resultLocation': 's3://prediction-services/score/',
 'runId': '0b0789ab-4dfa-4eca-b5df-f582c6a3ec0d',
 'scoreEndTs': None,
 'scoreStartTs': '2021-02-19T11:40:32.930903',
 'status': 'Running',
 'updateTs': '2021-02-19T11:40:32.427784'}
None
s3://prediction-services/score/

### Forecast

In [14]:
predDf = pd.read_csv(predLoc, sep=',', header = 0)
predDf.head()
##fhrDf.index = pd.to_datetime(fhrDf.index)
##print(tabulate(trainDf, headers='keys', tablefmt='psql'))

,forecast_date,34883-3350,53511-10483,53511-3199,53511-3553,53511-3802,19463-3243,53511-4773
0,2021-04-01,627278.344957,16718.817007,67147.236808,7936.673735,45283.528897,164020.066938,36039.692221
1,2021-05-01,627718.069081,16422.009309,71096.830707,8664.854207,46432.778264,156884.896005,34939.179289
2,2021-06-01,628107.962759,16770.018017,72731.297351,8637.896984,47561.653915,163917.820953,35779.524294
3,2021-07-01,628453.679674,16897.878396,75242.287270,8981.081624,48699.565052,164180.676417,35916.965989
4,2021-08-01,628760.230593,17100.900148,77421.419384,9142.835778,49833.469065,167678.535456,36308.971942

# Prediction: Using Previously Trained Model

In [28]:
scoringDict = {
        "scoring": {
            "score_name": "score-minimum-config-manager",
            "target_data_location": "s3://prediction_services/data/TrainingInputData_Transformed_Test_Sample_2.csv",
            "model_names": ["ARIMA"],
            "prediction_steps": 12,
            "prediction_count": 10,
            "train_run_id": "e5ff99ac-e260-49d0-934f-46c46d31f136"
        }
    }
predResponse = requests.post(Baseurl+ "/predictions", 
                         auth=(user, password),
                         data = json.dumps(scoringDict))

In [29]:
print(predResponse)
predStatus = predResponse.json()
print(pprint.pprint(predStatus))
predId = predStatus['runId']
print(predId)

<Response [200]>
{'runId': '20fcd3ab-9f30-4e52-9340-8b48981f1956', 'status': 'Created'}
None
20fcd3ab-9f30-4e52-9340-8b48981f1956

### Get Prediction Status

In [31]:
predResponse = requests.get(Baseurl+"/fetch_predictions/"+ predId,
                              auth=(user,password))    
print(predResponse)
predStatus = predResponse.json()
print(pprint.pprint(predStatus))
predId = predStatus['runId']
print(predId)

<Response [200]>
{'runId': '20fcd3ab-9f30-4e52-9340-8b48981f1956',
 'status': 'Failed',
 'status_message': 'Failed to write to S3'}
None
20fcd3ab-9f30-4e52-9340-8b48981f1956

### Fetch Prediction Results

In [32]:
predResponse = requests.get(Baseurl+"/predictions/"+ predId,
                              auth=(user,password))    
print(predResponse)
predResults = predResponse.json()
print(pprint.pprint(predResults))

<Response [200]>
{'resultLocation': 's3://prediction-services/score/',
 'runId': '20fcd3ab-9f30-4e52-9340-8b48981f1956',
 'scoreEndTs': '2021-02-17T03:57:54.286754',
 'scoreStartTs': '2021-02-17T03:57:54.109345',
 'status': 'Failed',
 'status_message': 'Failed to write to S3',
 'updateTs': '2021-02-17T03:57:54.028922'}
None